name: autoXVR
favicon: null
layout_spectrum: 0.48131039505824447
typography_spectrum: 0.12168042431585491
title: 'Extreme Automotive Virtual Reality '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a8a9a3'
    - '#000000'
    - '#eff1fd'
    - '#282735'
    - '#8fd4fd'
  brandStrength: 0.4756141188554466
  lightness: 0.6945808664895594
  saturation: 0.19437450706027448
  rhythmicContrast: 0.8519039091188461
purpose: []
